name: 'BuildAngularElements'
description: 'Action to build all angular elements in a given folder and concatenate them to a single bundle'
inputs:
   scan:
    description: Optional. Specify which directory (relative to the root) should be scanned for projects.
    required: false
    default: "./projects"
   output-folder:
    description: Optional. Specify in which directory (relative to the root) the elements should be placed.
    required: false
    default: "./elements"
outputs:
  output-folder: 
    description: 'The folder where the elements are placed after the build.'
runs:
  using: 'node12'
  main: 'lib/main.js'
